ccflags-y += -Wno-missing-prototypes -Wno-error=missing-prototypes
subdir-ccflags-y += -Wno-missing-prototypes -Wno-error=missing-prototypes

obj-y += ion_compat.o
obj-$(CONFIG_HI_VCODEC_VDEC_HI3660) += hi_vcodec/vdec/
obj-$(CONFIG_HI_VCODEC_VENC_HI3660) += hi_vcodec/venc/drv/venc/
